---
name: Config-Model-Xorg
version: 1.103
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: Xorg configuration tool based on Config::Model
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
requires:
  Config::Model: 0.633
  Log::Log4perl: 0
recommends:
  Config::Model::CursesUI: 0
  Config::Model::TkUI: 0
provides:
  Config::Model::Xorg:
    file: lib/Config/Model/Xorg.pm
    version: 1.103
  Config::Model::Xorg::Read:
    file: lib/Config/Model/Xorg/Read.pm
    version: 1.0899
  Config::Model::Xorg::Write:
    file: lib/Config/Model/Xorg/Write.pm
    version: 1.0899
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
