---
abstract: 'Xorg configuration model for Config::Model'
author:
  - 'Dominique Dumont'
build_requires:
  Module::Build: 0.34
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.34
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model-Xorg
recommends:
  Config::Model::CursesUI: 0
  Config::Model::TkUI: 0
requires:
  Config::Model: 1.260
  Exception::Class: 0
  Log::Log4perl: 1.11
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Config-Model-Xorg
  homepage: http://config-model.wiki.sourceforge.net
  repository: http://config-model.hg.sourceforge.net:8000/hgroot/config-model/config-model-xorg
version: 1.106
