---
name: Config-Model-Xorg
version: 0.502
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: Configuration model for xorg.conf
license: lgpl
requires:
  Config::Model: 0.610
  Log::Log4perl: 0
recommends:
  Config::Model::CursesUI: 0
provides:
  Config::Model::Xorg::Read:
    file: lib/Config/Model/Xorg/Read.pm
  Config::Model::Xorg::Write:
    file: lib/Config/Model/Xorg/Write.pm
generated_by: Module::Build version 0.26
