---
name: Config-Model-Xorg
version: 0.504
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: Configuration model for xorg.conf
license: lgpl
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Config::Model: 0.614
  Log::Log4perl: 0
recommends:
  Config::Model::CursesUI: 0
provides:
  Config::Model::Xorg:
    file: lib/Config/Model/Xorg.pm
    version: 1.001
  Config::Model::Xorg::Read:
    file: lib/Config/Model/Xorg/Read.pm
  Config::Model::Xorg::Write:
    file: lib/Config/Model/Xorg/Write.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
