---
name: Config-Model-Xorg
version: 0.5
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: ~
license: lgpl
requires:
  Config::Model: 0.606
  Log::Log4perl: 0
provides:
  Config::Model::Xorg::Read:
    file: lib/Config/Model/Xorg/Read.pm
  Config::Model::Xorg::Write:
    file: lib/Config/Model/Xorg/Write.pm
generated_by: Module::Build version 0.26
